# nixpacks.toml

[phases.setup]
nixPkgs = ["...", "...", "..."]
aptPackages = ["libffi-dev", "libcairo2", "libpango-1.0-0", "libpangocairo-1.0-0", "libgdk-pixbuf2.0-0", "libgirepository-1.0-1", "libxml2-dev", "libjpeg-dev", "libfontconfig1-dev"]